# Generated by Django 4.2.3 on 2023-09-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_todo_delete_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='duedate_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='duedate_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
